"use client";
import Link from "next/link";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
import { getViewer } from "../../lib/auth";
import { AdminPlaylistInput,AdminPreview,previewPlaylist,publishPlaylist } from "../../lib/admin";
const initial:AdminPlaylistInput={playlist:"",anilist:"",language:"English",audioType:"Sub",region:"Asia"};
export default function AdminPage(){
 const router=useRouter(),[input,setInput]=useState(initial),[preview,setPreview]=useState<AdminPreview|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(true),[authorized,setAuthorized]=useState(false);
 useEffect(()=>{getViewer().then(a=>{if(!a.isAdmin){setStatus("This account does not have administrator access.");return}setAuthorized(true)}).catch(()=>router.replace("/login?next=/admin")).finally(()=>setBusy(false))},[router]);
 function field<K extends keyof AdminPlaylistInput>(key:K,value:AdminPlaylistInput[K]){setInput(x=>({...x,[key]:value}));setPreview(null)}
 async function inspect(e:FormEvent){e.preventDefault();setBusy(true);setStatus("");try{const r=await previewPlaylist(input);setPreview(r.preview)}catch(x){setStatus(x instanceof Error?x.message:"Preview failed.")}finally{setBusy(false)}}
 async function publish(){setBusy(true);setStatus("");try{const r=await publishPlaylist(input);setStatus(`Published ${r.episodeCount} episodes.`);router.push(`/anime/${r.animeId}`)}catch(x){setStatus(x instanceof Error?x.message:"Publish failed.")}finally{setBusy(false)}}
 return <main className="adminPage"><header className="adminHeader"><Link href="/">← Catalogue</Link><div><span className="eyebrow">Private administration</span><h1>Catalogue console</h1><p>Validate an approved distributor playlist before publishing it.</p></div></header>{busy&&!authorized?<p className="status">Checking access…</p>:!authorized?<p className="status error">{status}</p>:<div className="adminLayout"><form className="adminForm" onSubmit={inspect}><label>YouTube playlist URL<input value={input.playlist} onChange={e=>field("playlist",e.target.value)} placeholder="https://www.youtube.com/playlist?list=…" required/></label><label>AniList URL or ID<input value={input.anilist} onChange={e=>field("anilist",e.target.value)} placeholder="https://anilist.co/anime/…" required/></label><div className="adminFields"><label>Language<input value={input.language} onChange={e=>field("language",e.target.value)} required/></label><label>Audio<select value={input.audioType} onChange={e=>field("audioType",e.target.value as AdminPlaylistInput["audioType"])}><option>Sub</option><option>Dub</option><option>Original</option></select></label><label>Region<input value={input.region} onChange={e=>field("region",e.target.value)} required/></label><label>Expected episodes<input type="number" min="1" value={input.expectedEpisodes??""} onChange={e=>field("expectedEpisodes",e.target.value?Number(e.target.value):undefined)}/></label></div><button disabled={busy}>{busy?"Validating…":"Preview import"}</button>{status&&<p className={status.startsWith("Published")?"status success":"status error"}>{status}</p>}</form>{preview&&<section className="adminPreview"><span className="eyebrow">Validation result</span><h2>{preview.anime.title.english??preview.anime.title.romaji}</h2><dl><div><dt>Distributor</dt><dd>{preview.channelName}</dd></div><div><dt>Playlist</dt><dd>{preview.playlistTitle}</dd></div><div><dt>Validated</dt><dd>{preview.validatedEpisodes} episodes</dd></div><div><dt>Range</dt><dd>{preview.firstEpisode}–{preview.lastEpisode}</dd></div><div><dt>AniList total</dt><dd>{preview.anime.episodeCount??"Unknown"}</dd></div></dl>{preview.warnings.length>0?<div className="adminWarnings"><strong>Not ready to publish</strong>{preview.warnings.map(w=><p key={w}>{w}</p>)}<p>Combined-season or mismatched playlists require manual splitting.</p></div>:<button className="publishButton" disabled={busy} onClick={publish}>Publish to catalogue</button>}</section>}</div>}</main>;
}
