"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { logout } from "../../lib/auth";
import { AdminPlaylistInput,AdminPreview,deleteAnime,previewPlaylist,publishPlaylist } from "../../lib/admin";
const initial:AdminPlaylistInput={playlist:"",anilist:"",language:"English",audioType:"Sub",region:"Asia"};
export default function CatalogueManager({email}:{email:string}){
 const router=useRouter(),[input,setInput]=useState(initial),[preview,setPreview]=useState<AdminPreview|null>(null),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[deleteId,setDeleteId]=useState("");
 async function removeAnime(){if(!deleteId||!window.confirm("Delete this anime and all attached episodes/sources? Playlist inventory will be preserved."))return;setBusy(true);try{await deleteAnime(deleteId);setStatus("Anime deleted; playlist inventory preserved.");setDeleteId("")}catch(e){setStatus(e instanceof Error?e.message:"Delete failed.")}finally{setBusy(false)}}
 async function signOut(){await logout();router.replace("/login?next=/manage");router.refresh()}
 function field<K extends keyof AdminPlaylistInput>(key:K,value:AdminPlaylistInput[K]){setInput(x=>({...x,[key]:value}));setPreview(null)}
 async function inspect(e:FormEvent){e.preventDefault();setBusy(true);setStatus("");try{const r=await previewPlaylist(input);setPreview(r.preview)}catch(x){setStatus(x instanceof Error?x.message:"Preview failed.")}finally{setBusy(false)}}
 async function publish(){setBusy(true);setStatus("");try{const r=await publishPlaylist(input);setStatus(`Published ${r.episodeCount} episodes.`);router.push(`/anime/${r.animeId}`)}catch(x){setStatus(x instanceof Error?x.message:"Publish failed.")}finally{setBusy(false)}}
 return <main className="adminPage"><header className="adminHeader"><Link href="/">← Catalogue</Link><div><span className="eyebrow">Private catalogue tools</span><h1>Catalogue Manager</h1><p>Signed in as {email}. Validate approved distributor playlists before publishing.</p><button type="button" onClick={signOut}>Sign out</button></div></header><div className="adminLayout"><form className="adminForm" onSubmit={inspect}><label>YouTube playlist URL<input value={input.playlist} onChange={e=>field("playlist",e.target.value)} placeholder="https://www.youtube.com/playlist?list=…" required/></label><label>AniList URL or ID<input value={input.anilist} onChange={e=>field("anilist",e.target.value)} placeholder="https://anilist.co/anime/…" required/></label><div className="adminFields"><label>Language<input value={input.language} onChange={e=>field("language",e.target.value)} required/></label><label>Audio<select value={input.audioType} onChange={e=>field("audioType",e.target.value as AdminPlaylistInput["audioType"])}><option>Sub</option><option>Dub</option><option>Original</option></select></label><label>Region<input value={input.region} onChange={e=>field("region",e.target.value)} required/></label><label>Expected episodes<input type="number" min="1" value={input.expectedEpisodes??""} onChange={e=>field("expectedEpisodes",e.target.value?Number(e.target.value):undefined)}/></label></div><button disabled={busy}>{busy?"Validating…":"Preview import"}</button>{status&&<p className={status.startsWith("Published")?"status success":"status error"}>{status}</p>}</form>{preview&&<section className="adminPreview"><span className="eyebrow">Validation result</span><h2>{preview.anime.title.english??preview.anime.title.romaji}</h2><dl><div><dt>Distributor</dt><dd>{preview.channelName}</dd></div><div><dt>Playlist</dt><dd>{preview.playlistTitle}</dd></div><div><dt>Validated</dt><dd>{preview.validatedEpisodes} episodes</dd></div><div><dt>Range</dt><dd>{preview.firstEpisode}–{preview.lastEpisode}</dd></div><div><dt>AniList total</dt><dd>{preview.anime.episodeCount??"Unknown"}</dd></div></dl>{preview.warnings.length>0?<div className="adminWarnings"><strong>Not ready to publish</strong>{preview.warnings.map(w=><p key={w}>{w}</p>)}<p>Combined-season or mismatched playlists require manual splitting.</p></div>:<button className="publishButton" disabled={busy} onClick={publish}>Publish to catalogue</button>}</section>}<section className="adminPreview"><span className="eyebrow">Catalogue maintenance</span><h2>Delete incorrect anime</h2><p>Paste the internal ID from the anime URL. Playlist inventory is preserved for remapping.</p><input value={deleteId} onChange={e=>setDeleteId(e.target.value)} placeholder="cmup…"/><button className="publishButton" disabled={busy||!deleteId} onClick={removeAnime}>Delete anime</button></section></div></main>;
}
